# @format

apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJek1USXlOakUwTkRjME5Gb1hEVE16TVRJeU5ERTBORGMwTkZvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS2pyCnF1U1NlaUZORGNQMFZneks4TFl4M3Q0SlRMYlNLYnNLWFpOT2RKK3hyMzc4TmMwYlUrM1BJZkRjam5ycm5GeWcKRmhTTjRFTWs4eTZLaHNFQnpibUJtUkgzck1wYUZ0bWc3UTF4bnRuR2dBMzh3M1YraHVkdlJLRjk5VVkyMUJSVQowbFU0Z2VWWXFGUzRuWU5POUQ3UDhNOTYvRVd3NFg5anNDT3ZYd2tqNE9nNEpLWWVLdHkweVlkbFpjNXZCYXk4CnJYRXdKT3JyZFc5T0c1VHpOblp2OUZGSWg3L2MzQmNnZGJQUGd5bW1vaEQ1ZFlkWnA3Qmk4V2JkUjRnZTJIR3EKdmNFdFBVczdxMXM4cDB4Y05FUTFnNHZHZG1oTTBjYjMzaENjUUxJY21iZ2xONlJTU3pJTktiMVBhSFRzM1d3cAorbFZzSnVjQWo3K1NicjRFYkJjQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJRNnlyMXZBekJRSDI0VkhGbTJ0c3p4UEJwdXdqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFjbXZDUmROaAprMUJGWVc4SFZtUmpYSTlKWTQ0MkJLeUV4VzloUm9TMDlDajF5WXdFTENwdndxZnRZZ1MxTytLVDNOallDanJOClRMTFdQK1l5a29EcU1hN1lrc2dEeXRKL1pyM0dRbTM1enpsOURTeW1oOTFEVVJLUzhLbXhoUFpNZE0xTnZWUXIKZlpsb0lWNnN0V0dScFRnUm1uZkFGQTdDN0ZLamthaTJNK0VzbHFKbnA5MjVNRFdoM2RDUnFXcDA5ZkxpakJ0YwpjQzh1cks4b285V1EzWUdlcUJnZnVvSEwvdmFjekU4eVJMR3p1d203bnlmUVVHS1ZiWVYrdWRGQ1NDV0cvNHljClF1dkszY3MyWFhhK3h6NnlVeEJGUmhDMzdqOVlIaG9NWUFLSmYzbXJEdVVwWlVXRXAwSjNCSktMdTZhSU9VMi8KRVFHY0MvaS9ITG1qcnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
      extensions:
        - extension:
            last-update: Wed, 27 Dec 2023 17:02:15 CET
            provider: minikube.sigs.k8s.io
            version: v1.32.0
          name: cluster_info
      server: https://87.6.226.202:56077
    name: minikube
contexts:
  - context:
      cluster: minikube
      extensions:
        - extension:
            last-update: Wed, 27 Dec 2023 17:02:15 CET
            provider: minikube.sigs.k8s.io
            version: v1.32.0
          name: context_info
      namespace: default
      user: minikube
    name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
  - name: minikube
    user:
      client-certificate-data: /Users/alibimini/.minikube/profiles/minikube/client.crt
      client-key-data: /Users/alibimini/.minikube/profiles/minikube/client.key
