# @format

name: Java Maven integrated build runtime

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build With Maven
        working-directory: ./siw-exam-individual
        run: |
          mvn -B package -DskipTests --file pom.xml
          cd target && ls -al

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build Docker Image
        working-directory: ./siw-exam-individual
        run: |
          docker build -t ${{secrets.DOCKER_USERNAME}}/testing-maven .
          docker push ${{secrets.DOCKER_USERNAME}}/testing-maven
          docker images

     # - name: K8s apply
      #  uses: FarBreaker/kubectl@v0.0.4
        #env:
       #   BASE64_KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
      #    KUBECTL_VERSION: "1.23.6"
     #   with:
    #      args: apply -f deployment.yml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    # uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
